package cmd

import "fmt"

func PrintHelp() {
	fmt.Printf("ti %s - Static type analyzer for MRuby\n\n", Version)
	fmt.Println("Usage:")
	fmt.Println("  ti <file.rb> [options]")
	fmt.Println()
	fmt.Println("Examples:")
	fmt.Println("  ti file.rb                          # Type check (outputs file.rb:::5:::TypeError)")
	fmt.Println("  ti file.rb --suggest --row=10        # Completion suggestions at row 10")
	fmt.Println("  ti file.rb --hover --row=5           # Hover info at row 5")
	fmt.Println("  ti file.rb --define --row=3          # Definition info at row 3")
	fmt.Println("  ti file.rb --extends --class=MyClass   # Class hierarchy for MyClass")
	fmt.Println("  ti file.rb --llm                     # Method signatures for LLM")
	fmt.Println("  ti --all-type                       # List all known types")
	fmt.Println()
	fmt.Println("Options:")
	fmt.Println("  -h, --help          Show this help message")
	fmt.Println("  -v, --version       Show version")
	fmt.Println("  -d                  Debug mode")
	fmt.Println("  --strict            Strict mode")
	fmt.Println()
	fmt.Println("LSP / Editor options:")
	fmt.Println("  -i                  Output method definition info")
	fmt.Println("  --define            Output all definition info")
	fmt.Println("  --suggest           Output completion suggestions")
	fmt.Println("  --hover             Output hover info")
	fmt.Println("  --extends           Output class hierarchy")
	fmt.Println("  --row=N             Target row number (used with --define, --suggest, --hover)")
	fmt.Println("  --class=NAME        Target class name (used with --extends)")
	fmt.Println()
	fmt.Println("LLM options:")
	fmt.Println("  --llm               Output method signatures and comments for LLM")
	fmt.Println("  --llm-error         Output errors for LLM")
	fmt.Println("  --llm-define --class=SomeClass        Output all definitions for LLM")
	fmt.Println("  --llm-class         Output all classes for LLM")
	fmt.Println()
	fmt.Println("Other options:")
	fmt.Println("  --all-type          List all known types")
}
